/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminEscolaRouteImport } from './routes/_authenticated/admin-escola'
import { Route as AuthenticatedCorrecaoRouteImport } from './routes/_authenticated/correcao'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedDevolutivasRouteImport } from './routes/_authenticated/devolutivas'
import { Route as AuthenticatedGabaritoRouteImport } from './routes/_authenticated/gabarito'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRelatoriosAlunosRouteImport } from './routes/_authenticated/relatorios-alunos'
import { Route as AuthenticatedRelatoriosQuestoesRouteImport } from './routes/_authenticated/relatorios-questoes'
import { Route as AuthenticatedTutoriaisRouteImport } from './routes/_authenticated/tutoriais'
import { Route as AuthenticatedAvaliacaoDiagnosticaIndexRouteImport } from './routes/_authenticated/avaliacao-diagnostica.index'
import { Route as AuthenticatedAvaliacaoDiagnosticaIdRouteImport } from './routes/_authenticated/avaliacao-diagnostica.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEscolaRoute =
  AuthenticatedAdminEscolaRouteImport.update({
    id: '/admin-escola',
    path: '/admin-escola',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorrecaoRoute = AuthenticatedCorrecaoRouteImport.update({
  id: '/correcao',
  path: '/correcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevolutivasRoute =
  AuthenticatedDevolutivasRouteImport.update({
    id: '/devolutivas',
    path: '/devolutivas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGabaritoRoute = AuthenticatedGabaritoRouteImport.update({
  id: '/gabarito',
  path: '/gabarito',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosAlunosRoute =
  AuthenticatedRelatoriosAlunosRouteImport.update({
    id: '/relatorios-alunos',
    path: '/relatorios-alunos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosQuestoesRoute =
  AuthenticatedRelatoriosQuestoesRouteImport.update({
    id: '/relatorios-questoes',
    path: '/relatorios-questoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutoriaisRoute = AuthenticatedTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacaoDiagnosticaIndexRoute =
  AuthenticatedAvaliacaoDiagnosticaIndexRouteImport.update({
    id: '/avaliacao-diagnostica/',
    path: '/avaliacao-diagnostica/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliacaoDiagnosticaIdRoute =
  AuthenticatedAvaliacaoDiagnosticaIdRouteImport.update({
    id: '/avaliacao-diagnostica/$id',
    path: '/avaliacao-diagnostica/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-escola': typeof AuthenticatedAdminEscolaRoute
  '/correcao': typeof AuthenticatedCorrecaoRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/devolutivas': typeof AuthenticatedDevolutivasRoute
  '/gabarito': typeof AuthenticatedGabaritoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-alunos': typeof AuthenticatedRelatoriosAlunosRoute
  '/relatorios-questoes': typeof AuthenticatedRelatoriosQuestoesRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/avaliacao-diagnostica/$id': typeof AuthenticatedAvaliacaoDiagnosticaIdRoute
  '/avaliacao-diagnostica/': typeof AuthenticatedAvaliacaoDiagnosticaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-escola': typeof AuthenticatedAdminEscolaRoute
  '/correcao': typeof AuthenticatedCorrecaoRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/devolutivas': typeof AuthenticatedDevolutivasRoute
  '/gabarito': typeof AuthenticatedGabaritoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-alunos': typeof AuthenticatedRelatoriosAlunosRoute
  '/relatorios-questoes': typeof AuthenticatedRelatoriosQuestoesRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/avaliacao-diagnostica/$id': typeof AuthenticatedAvaliacaoDiagnosticaIdRoute
  '/avaliacao-diagnostica': typeof AuthenticatedAvaliacaoDiagnosticaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aluno': typeof AlunoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-escola': typeof AuthenticatedAdminEscolaRoute
  '/_authenticated/correcao': typeof AuthenticatedCorrecaoRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/devolutivas': typeof AuthenticatedDevolutivasRoute
  '/_authenticated/gabarito': typeof AuthenticatedGabaritoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/relatorios-alunos': typeof AuthenticatedRelatoriosAlunosRoute
  '/_authenticated/relatorios-questoes': typeof AuthenticatedRelatoriosQuestoesRoute
  '/_authenticated/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/_authenticated/avaliacao-diagnostica/$id': typeof AuthenticatedAvaliacaoDiagnosticaIdRoute
  '/_authenticated/avaliacao-diagnostica/': typeof AuthenticatedAvaliacaoDiagnosticaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/reset-password'
    | '/admin'
    | '/admin-escola'
    | '/correcao'
    | '/cronograma'
    | '/devolutivas'
    | '/gabarito'
    | '/painel'
    | '/relatorios'
    | '/relatorios-alunos'
    | '/relatorios-questoes'
    | '/tutoriais'
    | '/avaliacao-diagnostica/$id'
    | '/avaliacao-diagnostica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno'
    | '/reset-password'
    | '/admin'
    | '/admin-escola'
    | '/correcao'
    | '/cronograma'
    | '/devolutivas'
    | '/gabarito'
    | '/painel'
    | '/relatorios'
    | '/relatorios-alunos'
    | '/relatorios-questoes'
    | '/tutoriais'
    | '/avaliacao-diagnostica/$id'
    | '/avaliacao-diagnostica'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aluno'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/admin-escola'
    | '/_authenticated/correcao'
    | '/_authenticated/cronograma'
    | '/_authenticated/devolutivas'
    | '/_authenticated/gabarito'
    | '/_authenticated/painel'
    | '/_authenticated/relatorios'
    | '/_authenticated/relatorios-alunos'
    | '/_authenticated/relatorios-questoes'
    | '/_authenticated/tutoriais'
    | '/_authenticated/avaliacao-diagnostica/$id'
    | '/_authenticated/avaliacao-diagnostica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlunoRoute: typeof AlunoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-escola': {
      id: '/_authenticated/admin-escola'
      path: '/admin-escola'
      fullPath: '/admin-escola'
      preLoaderRoute: typeof AuthenticatedAdminEscolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correcao': {
      id: '/_authenticated/correcao'
      path: '/correcao'
      fullPath: '/correcao'
      preLoaderRoute: typeof AuthenticatedCorrecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devolutivas': {
      id: '/_authenticated/devolutivas'
      path: '/devolutivas'
      fullPath: '/devolutivas'
      preLoaderRoute: typeof AuthenticatedDevolutivasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gabarito': {
      id: '/_authenticated/gabarito'
      path: '/gabarito'
      fullPath: '/gabarito'
      preLoaderRoute: typeof AuthenticatedGabaritoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios-alunos': {
      id: '/_authenticated/relatorios-alunos'
      path: '/relatorios-alunos'
      fullPath: '/relatorios-alunos'
      preLoaderRoute: typeof AuthenticatedRelatoriosAlunosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios-questoes': {
      id: '/_authenticated/relatorios-questoes'
      path: '/relatorios-questoes'
      fullPath: '/relatorios-questoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutoriais': {
      id: '/_authenticated/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof AuthenticatedTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacao-diagnostica/': {
      id: '/_authenticated/avaliacao-diagnostica/'
      path: '/avaliacao-diagnostica'
      fullPath: '/avaliacao-diagnostica/'
      preLoaderRoute: typeof AuthenticatedAvaliacaoDiagnosticaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacao-diagnostica/$id': {
      id: '/_authenticated/avaliacao-diagnostica/$id'
      path: '/avaliacao-diagnostica/$id'
      fullPath: '/avaliacao-diagnostica/$id'
      preLoaderRoute: typeof AuthenticatedAvaliacaoDiagnosticaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminEscolaRoute: typeof AuthenticatedAdminEscolaRoute
  AuthenticatedCorrecaoRoute: typeof AuthenticatedCorrecaoRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDevolutivasRoute: typeof AuthenticatedDevolutivasRoute
  AuthenticatedGabaritoRoute: typeof AuthenticatedGabaritoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRelatoriosAlunosRoute: typeof AuthenticatedRelatoriosAlunosRoute
  AuthenticatedRelatoriosQuestoesRoute: typeof AuthenticatedRelatoriosQuestoesRoute
  AuthenticatedTutoriaisRoute: typeof AuthenticatedTutoriaisRoute
  AuthenticatedAvaliacaoDiagnosticaIdRoute: typeof AuthenticatedAvaliacaoDiagnosticaIdRoute
  AuthenticatedAvaliacaoDiagnosticaIndexRoute: typeof AuthenticatedAvaliacaoDiagnosticaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminEscolaRoute: AuthenticatedAdminEscolaRoute,
  AuthenticatedCorrecaoRoute: AuthenticatedCorrecaoRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDevolutivasRoute: AuthenticatedDevolutivasRoute,
  AuthenticatedGabaritoRoute: AuthenticatedGabaritoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRelatoriosAlunosRoute: AuthenticatedRelatoriosAlunosRoute,
  AuthenticatedRelatoriosQuestoesRoute: AuthenticatedRelatoriosQuestoesRoute,
  AuthenticatedTutoriaisRoute: AuthenticatedTutoriaisRoute,
  AuthenticatedAvaliacaoDiagnosticaIdRoute:
    AuthenticatedAvaliacaoDiagnosticaIdRoute,
  AuthenticatedAvaliacaoDiagnosticaIndexRoute:
    AuthenticatedAvaliacaoDiagnosticaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlunoRoute: AlunoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
